en:
  setprefix:
    help: |
      Sets the server's cus0tom prefix (the original will still work). Requires the Manage Server permission. To use spaces in your prefix quote it.
      You can even use a space at the end of the prefix.
      
      Example 1 (no spaces):
      [p]setprefix splat!
      Example 2 (with trailing space):
      [p]setprefix "splat "
      
      To remove your server's prefix:
      [p]setprefix ""
    long: In order to prevent abuse to my disk, the custom prefix length has been capped at 10. Sorry!
    removed: removed
    changed: changed to `{}`
    set: set to `{}`
    formatted: Your server's custom prefix has been {}.